### ISSUE TITLE
(Feature request): Added feature to filter archives with less than n tags and scrape HenTag by ID list

### ISSUE THREAD

**Issue by nayumiDEV** [LetrixZ/faccina#27] opened 2024-11-12 10:16 UTC
There are some archives that do not have tags or have fewer tags than expected. I think there should be a feature to filter archives with the number of tags less than N (set by the user) to easily filter and update them. This should probably be added to the Admin Panel.

In addition, currently we can only use commands with ID or ranges of IDs, if you add use with lists of IDs (eg. [1, 2, 9, 100]) it will be better and easier to use when update archives.

**Comment by LetrixZ** [comment] 2024-11-12 14:47
> In addition, currently we can only use commands with ID or ranges of IDs, if you add use with lists of IDs (eg. [1, 2, 9, 100]) it will be better and easier to use when update archives.

Tried with `--ids 1,2,9,100`?

**Comment by nayumiDEV** [comment] 2024-11-12 15:43
> > In addition, currently we can only use commands with ID or ranges of IDs, if you add use with lists of IDs (eg. [1, 2, 9, 100]) it will be better and easier to use when update archives.
> 
> Tried with `--ids 1,2,9,100`?

ah, I don't know we can do that...

**Comment by LetrixZ** [comment] 2024-11-14 06:47
Added HenTag scraper [f74b9e6](https://github.com/LetrixZ/faccina/commit/f74b9e6c0849cb55f2dd33ed678a1fb3bdf115af)

**Comment by UBTL** [comment] 2024-12-05 21:13
Talking about tags, I downloaded some archives with Gallery-dl and I noticed that gallery-dl save the info.json metadata info inside the folder that downloaded the stuff while the indexer is expecting the file to be *outside* of the the (when you get it zipped)
![43545](https://github.com/user-attachments/assets/cde85ccc-58a8-424b-a2e1-0303b0e86067)

**Comment by LetrixZ** [comment] 2024-12-05 21:48
> Talking about tags, I downloaded some archives with Gallery-dl and I noticed that gallery-dl save the info.json metadata info inside the folder that downloaded the stuff while the indexer is expecting the file to be _outside_ of the the (when you get it zipped) ![43545](https://private-user-images.githubusercontent.com/105142453/392998189-cde85ccc-58a8-424b-a2e1-0303b0e86067.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0MzU1MDMsIm5iZiI6MTczMzQzNTIwMywicGF0aCI6Ii8xMDUxNDI0NTMvMzkyOTk4MTg5LWNkZTg1Y2NjLTU4YTgtNDI0Yi1hMmUxLTAzMDNiMGU4NjA2Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNVQyMTQ2NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNzFhMzA3NTk4MmRiZmRkMGMwODRlNGJmY2QwMWM3ZTFkMDhjMTY0OTBhYzBhZmIxYjY0MTVkZTY3MjAwZjkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.9j4Cofdc2Db86P5DNSDynQWHcFIEi-UDY9dkq85QpiA)

I can change it to get it from the root or if it doesn't find it, get the first one recursively.

Maybe I could also use that to delimit a gallery without needing it to be archived.

**Comment by UBTL** [comment] 2024-12-05 22:11
I would appreciate it I dont mind if you just tell me what I could possibly change if you dont want to commit this change to the repo if you do well once again I greatly appreciate it since I would rather not manually create new zip files for this dump I did with gallery-dl, if it was just 10-20 or so sure but the number is rather way more than that

**Comment by LetrixZ** [comment] 2024-12-06 05:29
@UBTL added in 892159c
As long as there is a root metadata file with the expected name `info.{json,yml,yaml}, ComicInfo.xml, booru.txt`, it will be detected as a gallery.

Example of a valid structure
```
content
├── Brought Together - Part One.cbz
├── Once A Happening
│   ├── 001.png
│   ├── 002.png
│   ├── 003.png
│   ├── 004.png
│   ├── 005.png
│   └── info.json
├── Source X
│   ├── From Another World
│   │   ├── 001.jpg
│   │   ├── 002.jpg
│   │   ├── 003.jpg
│   │   ├── 004.jpg
│   │   ├── 005.jpg
│   │   └── info.yaml
│   └── From Another World.yaml
└── Source Y
    ├── Surprise Me!
    │   ├── 1. Chapter One
    │   │   ├── 001.png
    │   │   ├── 002.png
    │   │   ├── 003.png
    │   │   ├── 004.png
    │   │   ├── 005.png
    │   ├── 2. Chapter 2
    │   │   ├── 006.png
    │   │   ├── 007.png
    │   │   ├── 008.png
    │   │   ├── 009.png
    │   │   ├── 010.png
    │   └── info.yaml
    └── Room Life.cbz
```

**Comment by LetrixZ** [comment] 2024-12-06 05:31
> There are some archives that do not have tags or have fewer tags than expected. I think there should be a feature to filter archives with the number of tags less than N (set by the user) to easily filter and update them. This should probably be added to the Admin Panel.

I'll see if I can add a syntax similar to the pages but for tags.

**Comment by LetrixZ** [comment] 2024-12-06 23:52
Added in 892159c...04fd698, you can now search by number of tags in general and by namespaces. Also added for size and for number of sources.
Example of a query: `tags>=2 artist>=1 circle>=1 size<=40M sources>=1`

**Comment by UBTL** [comment] 2024-12-08 00:59
Shouldnt have marked this one as closed yet for I have found issues, some not from just this lastest version, let's call previous Faccina version " Zip-only Faccina" and then this latest version.

In this latest version yeah the new code does in fact detect the info.json file in the folder and loads the tags on it, it doesnt if the folder is zipped though, I also tested some old Anchira/Koharu zip files which comes with its yaml file both in its cbz form and extracted and non of it get its metadata loaded, I tested it with the previous Zip-only Faccina too and the same happened

Talking about indexing folders, I dont know why but it only feels like indexing the folders it "vibes" with it, what does that mean? I dont know either, I thought maybe the normal e-hentai title formatting was breaking up stuff when it came of the folder version so I made folders with just [Artist] Title , but nope still not indexing, in Zip form though it doesnt care like usual, it will index it just fine whatever filename formatting it has.

Talking again reading Zips, this is more like suggestion but I was seeing the way the reader reads off the zip file and
![235252](https://github.com/user-attachments/assets/722d8e3a-ddc7-4bbe-b116-9deb50a8cbe9)
why the read after page 1 reads from 3 pages head of its current page? should read like say Page 2 is loaded and has already page 3 and 4 loaded in?

**Comment by UBTL** [comment] 2024-12-08 01:06
Oh yeah second suggestion (dont really feel like making an "issue" for it) but would be rather cool to have like a delete button to directly delete galleries, it would help clean up a lot, I though that maybe the "show/hide" button and then maybe the prune command would do something like that but no, it literally just shows/hides a gallery but you still keep all the duplicated galleries and you need to go and manually delete them, is fine if your collection is just a few hundred but when stuff well over 30K files and more, yeah it gets a pain imho, would be cool to have a delete button if possible, thank you very much

**Comment by LetrixZ** [comment] 2024-12-08 01:07
> why the read after page 1 reads from 3 pages head of its current page? should read like say Page 2 is loaded and has already page 3 and 4 loaded in?

There is preloading happening there. If the same image gets reloaded, it might be because the browser didn't cache them. I could add a setting to disable it.

---

As for the indexing, could you share me somewhere the content that causes these issues?

**Comment by UBTL** [comment] 2024-12-08 01:27
> There is preloading happening there. If the same image gets reloaded, it might be because the browser didn't cache them. I could add a setting to disable it.

Check the image again, is not the same image loading again, when reading a zip based gallery the reader reads also the third page from the current page but not the next one to the current page and the second next, and when its a folder based gallery it reads 2 pages ahead
![235252](https://github.com/user-attachments/assets/c133f44f-6ac1-403c-92d1-dc94ed61bd74)
![5467456745](https://github.com/user-attachments/assets/605e7583-ca9b-49fb-a423-f433dc313d60)

**Comment by LetrixZ** [comment] 2024-12-08 01:29
Ah. That should be fixed in 375402e

**Comment by LetrixZ** [comment] 2024-12-08 01:40
<img width="760" alt="images" src="https://github.com/user-attachments/assets/fb16a2c4-2e0b-49c3-81f0-47341f0d651d">

**Comment by UBTL** [comment] 2024-12-08 01:49
> As for the indexing, could you share me somewhere the content that causes these issues?

https://gofile.io/d/zDEEUd

**Comment by LetrixZ** [comment] 2024-12-08 02:43
> > As for the indexing, could you share me somewhere the content that causes these issues?
> 
> https://gofile.io/d/zDEEUd

- The metadata for the Anchira files only includes the URL source. Doesn't have any tags nor title. I'll fallback to the parsed filename title (or just the filename as title) in case no title was found in the available metadata.
- As for the Info JSON stuff, I'll do that of checking recursively for the `index.json` inside the ZIP and using the first match.
- The normal stuff doesn't have anything but the filename for its metadata.

I'll also try them in folder form to see if I can find any weird behavior.

**Comment by UBTL** [comment] 2024-12-08 02:53
I did just noticed the issue Anchira files and was starting to write about it since this files were downloaded directly from there and arent part of the Anchira dumps uploaded to nyaa that comes with a different type of info.yaml, not a surprise with how shady the Admin of that place is to begin with, I have assume he at least fucked to properly put metadata files on it however I loaded the Anchira files with proper info.json files and repack them and yeah, it still not loading the metadata files.
The normal files are named that, because they are just vanilla files, no metadata on it, they are for the indexing for extracted folders to see if it feel like indexing them or not , talking about indexing if you indexed a zip file, extract it, then delete the entry on the database, delete the file and hit the index command again, it wont index the newly created extracted folder

**Comment by LetrixZ** [comment] 2024-12-08 03:09
> loaded the Anchira files with proper info.json files and repack them and yeah, it still not loading the metadata files.

Did you put the `info.json` file on the same ZIP or created a new one that doesn't contain the original `info.yaml`? 
If you have both, `info.yaml` will have priority.

> talking about indexing if you indexed a zip file, extract it, then delete the entry on the database, delete the file and hit the index command again, it wont index the newly created extracted folder

So you did:
1. Put the ZIP file in the content directory
2. Indexed that file.
3. Extracted the file in the same place.
4. Deleted the entry created in step 2 from the database.
5. Deleted the ZIP file from the content directory.
6. Indexed again.

This won't work because there is not metadata file to tell the folder as an archive. I can try to check every folder in the content directory, scan folders that contain only images and try to index that but this could easily break if there are subfolders for chapters. I'll try this anyways.

A better approach if you don't have a metadata file and want to use folders, is that you could create a file name `.archive` or `_archive` to mark the root of the archive so it can be indexed. Would this approach serve you?

**Comment by UBTL** [comment] 2024-12-08 03:18
> Did you put the `info.json` file on the same ZIP or created a new one that doesn't contain the original `info.yaml`? If you have both, `info.yaml` will have priority.

Yes, I deleted the original essentially empty info.yaml file and loaded up a proper info.json file and then zipped that folder and index it, it didnt load the metadata

> So you did:
> 1. Put the ZIP file in the content directory
> 2. Indexed that file.
> 3. Extracted the file in the same place.
> 4. Deleted the entry created in step 2 from the database.
> 5. Deleted the ZIP file from the content directory.
> 6. Indexed again.

Yes I did

> This won't work because there is not metadata file to tell the folder as an archive. I can try to check every folder in the content directory, scan folders that contain only images and try to index that but this could easily break if there are subfolders for chapters. I'll try this anyways.

the folders does have an info.json too, it just doesnt index them, try doing it too with one of the zip files that has info.json added to it

**Comment by UBTL** [comment] 2024-12-08 03:22
> A better approach if you don't have a metadata file and want to use folders, is that you could create a file name .archive or _archive to mark the root of the archive so it can be indexed. Would this approach serve you?

As mentioned before, the folders has info.json to them, not loading the folder without a info.json in them I see it as a feature not a bug for the aforementioned things you mentioned regarding the possibilities of breaking stuff and the like, issue here is that isnt indexing the folders with info.json in them regardless

**Comment by UBTL** [comment] 2024-12-08 03:28
Also just in case since I forget that Faccina does 2 types of databases, I have been talking about the PostgreSQL version here, dunno if the issues also happen on the SQLite version

**Comment by LetrixZ** [comment] 2024-12-08 03:38
@UBTL can you confirm that this is the structure that you have?
These indexed properly for me, even if I put them at the same level.

```
content/
├── Anchira
│   ├── [Tearontaron] Love Comes After the Storm (Comic Kairakuten 2023-06)
│   │   ├── 001.png
│   │   ├── 002.png
│   │   ├── 003.png
│   │   └── info.yaml # original
│   └── [Tearontaron] The Most Mismatched Couple Around
│       ├── 001.png
│       ├── 002.png
│       ├── 003.png
│       └── info.yaml # original
├── InfoJSON
│   ├── [Futa] Maid x Tenshu (Touhou Project) [English] [Uncle Bane]
│   │   ├── 01_p0.png
│   │   ├── 02_p1.jpg
│   │   ├── 03_p2.jpg
│   │   └── info.json # original
│   └── [sora wa chimidoro (jackasss)] Hajime no Ushiwakamaru First time with Ushiwakamaru
│       ├── 001.jpg
│       ├── 002.png
│       ├── 003.png
│       └── info.json # original
└── Normal
    ├── [LUXsumildo] Garen's Bitch (League of Legends) [English] [Uncle Bane] (Uncensored)
    │   ├── 001.webp
    │   ├── 002.webp
    │   ├── 003.webp
    │   └── info.json # downloaded with the ExResurrect userscript
    └── [Ooshima Ryou] LIFE (COMIC Megastore H 2010-08) [English]
        ├── 001.jpg
        ├── 002.jpg
        ├── 003.jpg
        └── info.json # downloaded with the ExResurrect userscript
```
<img width="546" alt="image" src="https://github.com/user-attachments/assets/a7a20a8e-069b-4b4e-b094-b981c1296f93">
<img width="1521" alt="image" src="https://github.com/user-attachments/assets/638ecba1-fbf1-465f-9ae6-82b92ed80cf7">

**Comment by LetrixZ** [comment] 2024-12-08 03:43
The one by jackasss didn't index properly...

**Comment by UBTL** [comment] 2024-12-08 03:49
Yeah was going to point that out, also because of how of a low number of files I shared is not unusual for most if not all of them to actually index, but that is because we are not dealing with a dump of
![Screenshot - 2024-12-07T214748 221](https://github.com/user-attachments/assets/2257ab02-f272-4d9c-af86-7c9a3d0b519f)

So when I index a next batch of stuff, it can be like a hundred files (of them in folder form) and it only felt like indexing 40 or so of them if it felt generous

**Comment by LetrixZ** [comment] 2024-12-08 04:04
@UBTL changed the way JSON schemas are determined. That fixed the one by jackass for me.

I'll see if I can find a better way to get data from metadata so it isn't limited to fixed schemas.

**Comment by LetrixZ** [comment] 2024-12-08 04:13
> it only felt like indexing 40 or so of them if it felt generous

This one is weird. As long as it can be determined that it is an archive, it will be indexed, even if there is not valid metadata present (with the exception of folders).

Can you try indexing a subset where you know some of then fail to index and run the command with `-v` or `--verbose`?
It should tell you why some of them weren't indexed.

**Comment by UBTL** [comment] 2024-12-08 04:36
> This one is weird. As long as it can be determined that it is an archive, it will be indexed, even if there is not valid metadata present (with the exception of folders).

 We have been talking mainly about extracted folders stuff after all with zipped files having still some quirks second pretty much, I clearly mentioned when it comes to zip files, it doent even care what filename or if it has a metadata file in it or not, it gets indexed (as long as it isnt one of the few zip files that used exoteric compression algorithm you mentioned a while ago)
Will check again later since I need to go other stuff now, also will remind again about the possibility of a delete button if possible for sanity sake but I will leave it as low priority otherwise

**Comment by LetrixZ** [comment] 2024-12-08 05:21
Added the delete button besides show/hide with the following default config:
```toml
[site.admin]
delete_require_confirmation = true
```

**Comment by UBTL** [comment] 2024-12-08 07:23
New version give me these errors when building
200 |   #onClose(e) {
201 |     this.#onExitPromise = e.code, this.emit("exit", e.code);
202 |   }
203 |   #onError(event) {
204 |     let error = event?.error;
205 |       error = new Error(event.message, { cause: event });
                    ^
error: 159 |     const json = JSON.stringify(obj, null, 2);
160 |     return json.replace(/"([^"]+)":/g, "$1:");
161 | };
162 | class ZodError extends Error {
163 |     constructor(issues) {
164 |         super();
              ^
ZodError: [
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "undefined",
    "path": [
      "image",
      "preset",
      "cover",
      "label"
    ],
    "message": "Required"
  },
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "undefined",
    "path": [
      "image",
      "preset",
      "thumbnail",
      "label"
    ],
    "message": "Required"
  }
]
 errors: [
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "undefined",
    "path": [
      "image",
      "preset",
      "cover",
      "label"
    ],
    "message": "Required"
  },
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "undefined",
    "path": [
      "image",
      "preset",
      "thumbnail",
      "label"
    ],
    "message": "Required"
  }
]

**Comment by UBTL** [comment] 2024-12-08 07:26
![54737377](https://github.com/user-attachments/assets/b81a57c7-0ce4-4618-9a98-fc184dade08c)

**Comment by LetrixZ** [comment] 2024-12-08 07:27
A label is now required for image presets. I forgot to make it optional.

**Comment by UBTL** [comment] 2024-12-08 20:10
Oh right got it, just wrote label = 'cover' and label = 'thumb' respectively for both of them, dunno if that was good or not but it is working fine so far
![ab67616d0000b27302f6dfc717457d4d55f9c8fc](https://github.com/user-attachments/assets/093de9c3-7d2f-4a3e-a4d9-8d14c2bd62a2)

So then so far I think everything needed to be done is done so far then (just perhaps gonna need to update the readme file about those changes at some point I would guess)

**Comment by LetrixZ** [comment] 2024-12-08 22:31
> (just perhaps gonna need to update the readme file about those changes at some point I would guess)

Yeah. Added a lot of stuff but hasn't kept the README updated.

So then, is the indexing issue fixed?

**Comment by UBTL** [comment] 2024-12-08 23:02
With the latest new version, I think it does so far? loaded 2 new batches and for now it seems to behave so far, delete button for sure is great thing that Im going blasting off dupes
![danny-devito-guns](https://github.com/user-attachments/assets/fce2ae1a-61a9-4cd5-b460-b7c26ad50dc6)

**Closed as completed** 2024-12-08 23:03 UTC
